export const HELLO_WORLD = "HELLO_WORLD"


export const BOARDS_FETCH = "BOARDS_FETCH"
export const BOARDS_FETCH_SUCCESS = "BOARDS_FETCH_SUCCESS"
export const BOARDS_FETCH_FAILURE = "BOARDS_FETCH_FAILURE"

export const BOARD_FETCH = "BOARD_FETCH"
export const BOARD_FETCH_SUCCESS = "BOARD_FETCH_SUCCESS"
export const BOARD_FETCH_FAILURE = "BOARD_FETCH_FAILURE"
